name: Update NWS Zones and Release

on:
  schedule:
    - cron: '0 */48 * * *'  # Every 48 hours
  workflow_dispatch:

jobs:
  update-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch NWS zones data
        run: |
          curl -o nws-zones.json https://api.weather.gov/zones?include_geometry=false

      - name: Commit updated zones file
        uses: EndBug/add-and-commit@v7
        with:
          add: 'nws-zones.json'
          message: 'Update NWS zones data'
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'nws-zones.json'
          token: ${{ secrets.GITHUB_TOKEN }}
